version: "3.8"

services:
  audiobook_creator:
    build:
      context: ../..
      dockerfile: docker/cpu/Dockerfile
    container_name: audiobook_creator
    volumes:
      - ../..:/app
      - ../../model_cache:/app/model_cache
    env_file:
      - ../../.env
    restart: always
    # network_mode: host
    ports:
      - "7860:7860"


