version: "3.8"

services:
  audiobook_creator:
    build:
      context: ../..
      dockerfile: docker/gpu/Dockerfile
    container_name: audiobook_creator
    volumes:
      - ../..:/app
      - ../../model_cache:/app/model_cache
    env_file:
      - ../../.env
    restart: always
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  fastapi:
    image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.2.2
    container_name: kokoro_service
    restart: always
    network_mode: host
    profiles:
      - kokoro
    command: >
      uvicorn api.src.main:app --host 0.0.0.0 --port 8880 --log-level debug --workers ${MAX_PARALLEL_REQUESTS_BATCH_SIZE:-1}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
